### ISSUE TITLE
Utility programs

### ISSUE THREAD

**Issue by Pedro-sm** [MarkusFANUC/BasePMC#4]
Hello.
About utility versions, what kind of file we have to copy to the folder? Compressed or uncompressed?
For example, in gawk utility,, we have this different kind of file:
gawk-3.1.6-1-src.zip	
gawk-3.1.6-1-src-setup.exe	
gawk-3.1.6-1-setup.exe	
gawk-3.1.6-1-doc.zip	
gawk-3.1.6-1-bin.zip

And other question. In coreutils, i can not find any date or sleep part. How can I find?

**Comment by MarkusFANUC** [comment]
Hi Predro, 

you want to put the .exe into the utils older. Also, please don't use the latest (trunk) version of the BasePMC, since I am currently working on a redesign, that does no longer need the coreutils.

You can mail me at markus.birkhold(at)fanuc.eu and I can send you the corresponding .exe files in a passworded .zip for your convenience. We just don't want to share them due to potential licensing issues.

Yours,
Markus
